### ISSUE TITLE
Unable to load myo64 from system directories

### ISSUE THREAD

**Issue by akhibam** [NicholasAStuart/myo-java#11]
Hi there, I'm using your example to study how to extract EMG Data from Myo. I just copy the whole project and put in specified place in workspace. It seems I cant even run the project. I get this error:

Unable to load myo64 from system directories.
Unable to load myo32 from system directories.
Error: 
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Unknown Source)
	at java.nio.file.Files.copy(Unknown Source)
	at com.thalmic.myo.Hub.copyAndLoadX64FromTemp(Hub.java:187)
	at com.thalmic.myo.Hub.loadJniResources(Hub.java:67)
	at com.thalmic.myo.Hub.<init>(Hub.java:27)
	at com.thalmic.myo.example.EmgDataSample.main(EmgDataSample.java:11)

Is it because im not placing the resources at the right place? Please guide me sir.

My system using Windows 7, Eclipse Mars v4.5

Java version:

java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

**Comment by akhibam** [comment]
[SOLVED]

I forgot to add the DLL files into my project's java build path.

Right click on your project:

Properties > Java Build Path > Source > double click your project name >

Click Native Library Location > Edit to DLL location file > Done

**Comment by NicholasAStuart** [comment]
Glad to hear you got it working.
