### ISSUE TITLE
onArmSync not working: myo-java version 0.9.0

### ISSUE THREAD

**Issue by hvijayar** [NicholasAStuart/myo-java#12]
It seems event onArmSync is not working in myo-java version 0.9.0
   Environment: PC, Windows 7 enterprise, Eclipse.
   Myo SDK version: Windows SDK 0.9.0   (Jun 10, 2015)
   Myo Connect for Windows 1.0.1   (Sep 18, 2015)
Please check

**Comment by NicholasAStuart** [comment]
What do you mean "not working"? Are you just not receiving events, or is it crashing?

**Comment by hvijayar** [comment]
I am not receiving events.

**Comment by NicholasAStuart** [comment]
Fixed with ad92f33d82fb911c81fd89516edf7a3eb4cb1dcc

**Comment by hvijayar** [comment]
Thanks. I will check it out
