### ISSUE TITLE
onPose does not get called

### ISSUE THREAD

**Issue by jonas-db** [NicholasAStuart/myo-java#13]
Hi,

we are using version 0.9.1 on mac OSX Yosemite 10.10.5 and we are running the HelloMyo example but the onPose method does not get called when doing poses, it always prints "REST"

**Comment by NicholasAStuart** [comment]
What is your LockingPolicy? Are you performing the Unlock Gesture? By default, the LockingPolicy will require you to perform the unlock gesture before gestures are recognised by the onPose() method. If you set the Locking Policy to LOCKING_POLICY_NONE than you will get all poses without having to perform the unlock gesture.

**Comment by jonas-db** [comment]
The policy was wrong indeed, it works now.
