### ISSUE TITLE
MAC adress

### ISSUE THREAD

**Issue by zaagman** [NicholasAStuart/myo-java#17]
Dear Nicholas,

I'm hoping you can help me. I'm trying to connect 2 myo's to my Mac and use them to generate sound for a theatreproduction. I'm looking for a way to identify the myos on connecting and I would like to identify them by MAC adress. I see this is possible in the 0.10.0 Android SDK but not yet for your library. 

Could you tell me if you have any plans to implement that feature?

I'm looking forward to your reaction.

Best,
Maarten

**Comment by NicholasAStuart** [comment]
[Documentation for the Library for PC/OSX](https://developer.thalmic.com/docs/api_reference/platform/classmyo_1_1_myo.html) doesn't include the same methods as the [documentation for the library for Android](https://developer.thalmic.com/docs/api_reference/android/classcom_1_1thalmic_1_1myo_1_1_myo.html)

I'm not able to implement a getMacAddress() feature on Myo until Thalmic gives everyone access on PC.

**Comment by zaagman** [comment]
Hi Nicholas,

Thank you for your reaction and for linking me to the pc/osx library! I found that the .toString() function gives me a unique string for each armband. Also it is always the same, even if the armbands reboot. I don't know if this is the MAC adres but this is just the thing I need.

Best,
Maarten
