### ISSUE TITLE
Quaternion conjugate wrong

### ISSUE THREAD

**Issue by whyloop** [NicholasAStuart/myo-java#9]
The method Quaternion.conjugate() returns a Quaternion with all four(!) coordinates multiplied by -1. The real part should not be changed, though. (If the method is intended to do the quationion conjugation.)

**Comment by NicholasAStuart** [comment]
You are correct! I miscopied from the Thalmic example(_ and - look so similar). I'll fix this, thank you.

**Comment by NicholasAStuart** [comment]
Fixed in 81b647376bff4864bdc0dab98ec5456c41f73b36
